name: CD - Deploy DEV

on:
  workflow_run:
    workflows: [ Pulsedesk CI - Docker Build & Runtime Check ]
    types:
      - completed
    branches:
      - main
      - feature/*
  workflow_dispatch: 

jobs:
  deploy:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: MY_ECR_REPOSITORY
      ECS_SERVICE: MY_ECS_SERVICE
      AWS_REGION: us-east-1
    
    strategy:
      matrix:
        include:
          - service: backend
            context: ./apps/backend
            repository: pulsedesk-backend

          - service: analytics-service
            context: ./apps/analytics-service
            repository: pulsedesk-analytics

          - service: frontend
            context: ./apps/frontend
            repository: pulsedesk-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
      
      - name: Build, tag, and push image to Amazon ECR 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.repository }}
          IMAGE_TAG_SHA: sha-${{ github.sha }}
        run: |
          echo "Building $ECR_REPOSITORY from ${{ matrix.context }}"

          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            ${{ matrix.context }}

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA" >> $GITHUB_OUTPUT