name: Pulsedesk CI Tests Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  test:
    name: Run tests for all services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [backend, frontend, analytics-service]
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          # cache: 'npm'
          # cache-dependency-path: app/${{ matrix.service }}/package-lock.json
      
      - name: Cache NPM dependencies
        id: npm-cache
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ matrix.service }}-${{ hashFiles(format('app/{0}/package-lock.json', matrix.service)) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install Dependencies
        run: |
          cd app/${{matrix.service}}
          npm ci

      - name: Run Unit Tests
        run: |
          cd app/${{matrix.service}}
          npm test

      - name: Run Coverage (if present)
        run: |
          cd app/${{matrix.service}}
          npm run test:coverage --if-present


