name: Pulsedesk CI Tests Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
  workflow_dispatch:
  

jobs:
  test:
    name: Run tests for all services
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        service: [backend, frontend, analytics-service]
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      
      - name: Cache NPM dependencies
        id: npm-cache
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ matrix.service }}-${{ hashFiles(format('apps/{0}/package-lock.json', matrix.service)) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          cd apps/${{matrix.service}}
          npm install

      - name: Run Unit Tests
        continue-on-error: true
        run: |
          cd apps/${{matrix.service}}
          npm test

      - name: Run Coverage (if present)
        run: |
          cd apps/${{matrix.service}}
          npm run test:coverage --if-present
        
      - name: NPM Audit
        continue-on-error: true
        run: |
          cd apps/${{matrix.service}}
          npm audit --audit-level=high

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test_Results
          path: cd apps/${{matrix.service}}/results.xml

  containerization:
    name: Containerization
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            -t pulsedesk-${{ matrix.service }} \
            ./apps/${{ matrix.service }}




