name: Pulsedesk CI Tests Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
  workflow_dispatch:
  

jobs:
  test:
    name: Run tests for all services
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        service: [backend, frontend, analytics-service]
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          # cache: 'npm'
          # cache-dependency-path: apps/${{ matrix.service }}/package-lock.json
      
      - name: Cache NPM dependencies
        id: npm-cache
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ matrix.service }}-${{ hashFiles(format('apps/{0}/package-lock.json', matrix.service)) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          cd apps/${{matrix.service}}
          npm install

      - name: Run Unit Tests
        continue-on-error: true
        run: |
          cd apps/${{matrix.service}}
          npm test

      - name: Run Coverage (if present)
        run: |
          cd apps/${{matrix.service}}
          npm run test:coverage --if-present
        
      - name: NPM Audit
        continue-on-error: true
        run: npm audit --audit-level=high



